swagger: "2.0"
info:
  description: "This is Student Course Registration Portal. You can list courses and students.Get Student/Course Details. Add/Delete new Courses/Students"
  version: "1.0.0"
  title: "Swagger Student-Course-Registration"
  contact:
    email: "mcheekot@uncc.edu"
  
host: "68.183.144.13:8080"
tags:
- name: "student"
  description: "Everything about University Students"
  externalDocs:
    description: "Find out more"
    url: "http://uncc.edu"
- name: "course"
  description: "Access to University Courses"
schemes:
- "http"
paths:
  /students:
    get:
      tags:
      - "student"
      summary: "Get all students"
      description: "Returns array of students"
      operationId: "getStudents"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          type: "array"
          schema:
            $ref: "#/definitions/Student"
    post:
      tags:
      - "student"
      summary: "Add a new student to the portal"
      description: ""
      operationId: "addStudent"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Student object that needs to be added to the Portal"
        required: true
        schema:
          $ref: "#/definitions/Student"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Student"
        404:
          description: "Course Not Found"
      
  
  /student/{studentId}:
    get:
      tags:
      - "student"
      summary: "Find student by ID"
      description: "Returns a single student"
      operationId: "getStudentById"
      produces:
      - "application/json"
      parameters:
      - name: "studentId"
        in: "path"
        description: "ID of student to return"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Student"
        404:
          description: "Student not found"
    
    delete:
      tags:
      - "student"
      summary: "Deletes a student"
      description: ""
      operationId: "deleteStudent"
      produces:
      - "application/json"
      parameters:
      - name: "studentId"
        in: "path"
        required: true
        type: "integer"
      responses:
        500:
          description: "Error in Database Operation"
        
  /courses:
    get:
      tags:
      - "course"
      summary: "Get all courses"
      description: "Returns array of courses along with count"
      operationId: "getCourses"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          type: "array"
          schema:
            $ref: "#/definitions/Course"
    post:
      tags:
      - "course"
      summary: "Add a new course to the portal"
      description: ""
      operationId: "addCourse"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Course object that needs to be added to the Portal"
        required: true
        schema:
          $ref: "#/definitions/Course"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Course"
        404:
          description: "Course Not Found"
      
  
  /course/{courseId}:
    get:
      tags:
      - "course"
      summary: "Find Course by ID"
      description: "Returns a single Course"
      operationId: "getCourseById"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        in: "path"
        description: "ID of course to return"
        required: true
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Course"
        404:
          description: "Course not found"
    
    delete:
      tags:
      - "course"
      summary: "Deletes a course"
      description: ""
      operationId: "deleteCourse"
      produces:
      - "application/json"
      parameters:
      - name: "courseId"
        in: "path"
        required: true
        type: "integer"
      responses:
        500:
          description: "Error in Database Operation"

definitions:
  Course:
    type: "object"
    required:
    - "courseId"
    - "name"
    - "professor"
    properties:
      courseId:
        type: "integer"
      name:
        type: "string"
      professor:
        type: "string"
      department:
        type: "string"
        default: 'Computer Science'
      credits:
        type: "integer"
        default: 3
  
  Student:
    type: "object"
    required:
    - "name"
    - "photoUrls"
    properties:
      studentId:
        type: "integer"
      fName:
        type: "string"
        example: "Manik Prabhu"
      lName:
        type: "string"
      department:
        type: "string"
        default: "Computer Science"
      courseId:
        type: "string"
  